print("Enter first number")
n1 = input()
print("enter second number")
n2 = input()
print("Sum of these two numbers is", int(n1) + int(n2))
print("multiple of these two numbers is", int(n1) * int(n2))
print("divide of these two numbers is", int(n1) / int(n2))
print("subtraction of these two numbers is", int(n1) - int(n2))
print("subtraction of these two numbers is", int(n1) - 10 * int(n2))
print("subtraction of these two numbers is", 100 * int(n1) - 10 * int(n2))
print("subtraction of these two numbers is", 200 / int(n1) * 10 * int(n2))
print("subtraction of these two numbers is", 1000 * int(n1) * 10 * int(n2) + 5 * int(n2))
print("subtraction of these two numbers is", 100 + int(n1) * 10 / int(n2) + 5 * int(n2))
print("subtraction of these two numbers is", 100 + int(n1) * 10 - int(n2) + 5 * int(n2))
print("subtraction of these two numbers is",  int(n1) * 10 +1000/ int(n2) + 5 * int(n2))